### ISSUE TITLE
On centos/xfce, Xserver no longer starts

### ISSUE THREAD

**Issue by brianmajor** [ConSol/sakuli#341] opened 2019-02-14 22:09 UTC
If you build the centos/xfce container it no longer functions.  It appears that the xserver fails to initialize.  I suspect this is due to same change in upstream centos libraries, but am not certain.

The ubuntu/xfce container is working fine.

I believe this started happening just this week.

**Comment by s1hofmann** [comment] 2019-02-15 14:01
Did you do a clean rebuild of one of the Sakuli images? 
There has been an upstream change which affects our headless VNC images, but Sakuli images are based off our latest stable VNC images v1.3.0 which should be stable?

**Comment by brianmajor** [comment] 2019-02-15 18:02
Yes, I did a clean rebuild of https://github.com/ConSol/docker-headless-vnc-container (centos/xfce).

(I'm realizing now that I posted the issue to the wrong repository, sorry)

**Comment by s1hofmann** [comment] 2019-02-15 18:13
No problem. Regarding your issue, yes, that's a problem caused by an upstream change. (See [#108](https://github.com/ConSol/docker-headless-vnc-container/issues/108).
It's already fixed in `dev` and there will be a new release at the end of this month.

**Closed by s1hofmann** 2019-02-15 18:13 UTC

**Comment by brianmajor** [comment] 2019-02-15 18:23
Great, thanks very much.
