### ISSUE TITLE
Forwarder quick test mode

### ISSUE THREAD

**Issue by simonmeggle** [ConSol/sakuli#281] opened 2017-09-21 06:32 UTC
Implement a mode which allows to test a configured forwarder quickly.
Instead of executing `sakuli run [suite dir]` one could execute `sakuli fwd-test [suite dir]`, which reads the forwarder config from a suite dir without executing the suite.

**Comment by toschneck** [comment] 2017-10-13 08:11
duplicate of #141

**Closed by toschneck** 2017-10-13 08:11 UTC
Labels: area:forwarder
